spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mainPro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: CITIZEN-API
